# Generated by Django 3.2.9 on 2022-06-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('commentdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dowload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(default='game', max_length=120)),
                ('uploaddate', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('icon', models.FileField(upload_to='storeitemicon')),
                ('makepub', models.BooleanField(default=False)),
                ('visibility', models.CharField(default='public', max_length=100)),
                ('presentation', models.FileField(upload_to='presentation')),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.comment')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.like')),
            ],
        ),
    ]
