# Generated by Django 3.2.9 on 2022-06-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_dowload_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='like',
        ),
    ]
