# Generated by Django 3.2.9 on 2022-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220605_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Downloadpricing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='allowdownload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='offlinepricing',
            field=models.FloatField(default=0),
        ),
    ]
