# Generated by Django 3.2.9 on 2022-06-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220609_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='offlinepricing',
            new_name='onlinepricing',
        ),
        migrations.AddField(
            model_name='item',
            name='overview',
            field=models.FileField(blank=True, upload_to='overviewitem'),
        ),
    ]
